"""A campaign is a directory holding one model's optimization lineage.

Layout (created by `fast-kernel init`):

    GOAL.md            objective + policies (frontmatter) -- protected
    spec.py            ModelSpec: loader, workloads, oracle comparison -- protected
    candidate/         THE ONLY AGENT-OWNED CODE: apply(model, ctx) + kernels/
    experiments/NNNN-* one folder per experiment: metrics, gates, profile, log, patch
    results.tsv        ledger (tab separated)
    KNOWLEDGE.md       accumulated learnings (what worked / did not, with numbers)
    PLAN.md            rendered hotspot plan (regenerated by `profile`)
    hotspots.json, capabilities.json
    .fast-kernel/      state.db (SQLite), incumbent.json, loop.active, control flags

Lineage is git: the campaign directory is its own repository; every accepted experiment is a
commit on branch `fast-kernel/<model>` tagged `exp-N`, every rejected one is reset to the
incumbent (its patch is kept under experiments/). Each experiment therefore builds on top of
the previous accepted one -- the autoresearch keep/revert contract.
"""
from __future__ import annotations

import fnmatch
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .config import GoalConfig, load_goal
from .store import Store
from .util import now_iso, read_json, run, write_json

CAMPAIGN_IGNORE = """# managed by fast-kernel
experiments/
.fast-kernel/
results.tsv
KNOWLEDGE.md
PLAN.md
hotspots.json
capabilities.json
report.html
__pycache__/
*.pyc
*.log
.pytest_cache/
.triton/
"""


@dataclass
class Incumbent:
    number: int = -1
    commit: str = ""
    value: float | None = None
    metrics: dict[str, Any] = field(default_factory=dict)
    noise_floor: float = 0.0
    updated_at: str = ""
    anchor_ratio: float | None = None   # reference_ms / incumbent_ms, measured interleaved in one process
    anchor_uncertainty: float = 0.0     # relative ~95 % half-width of that ratio
    banked: int = 0                     # committed improvements too small to promote the incumbent yet

    def to_dict(self) -> dict[str, Any]:
        return self.__dict__.copy()

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> Incumbent:
        if not data:
            return cls()
        return cls(**{k: data.get(k, getattr(cls(), k)) for k in cls().__dict__})


class Campaign:
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        self.goal_path = self.root / "GOAL.md"
        self.spec_path = self.root / "spec.py"
        self.candidate_dir = self.root / "candidate"
        self.experiments_dir = self.root / "experiments"
        self.state_dir = self.root / ".fast-kernel"
        self.results_path = self.root / "results.tsv"
        self.knowledge_path = self.root / "KNOWLEDGE.md"
        self.plan_path = self.root / "PLAN.md"
        self.hotspots_path = self.root / "hotspots.json"
        self.capabilities_path = self.root / "capabilities.json"
        self.incumbent_path = self.state_dir / "incumbent.json"
        self.db_path = self.state_dir / "state.db"
        self._goal: GoalConfig | None = None
        self._store: Store | None = None

    # ---- discovery ---------------------------------------------------------------------
    @classmethod
    def find(cls, start: Path | None = None) -> Campaign | None:
        """Walk up from `start` to find a campaign; also look one level down (campaigns/<x>)."""
        here = Path(start or os.getcwd()).resolve()
        for candidate in [here, *here.parents]:
            if (candidate / "GOAL.md").exists() and (candidate / "candidate").exists():
                return cls(candidate)
        env = os.environ.get("FAST_KERNEL_CAMPAIGN")
        if env and (Path(env) / "GOAL.md").exists():
            return cls(Path(env))
        return None

    @classmethod
    def discover_all(cls, root: Path, max_depth: int = 3) -> list[Campaign]:
        found: list[Campaign] = []
        root = Path(root).resolve()
        for dirpath, dirnames, filenames in os.walk(root):
            depth = len(Path(dirpath).relative_to(root).parts)
            dirnames[:] = [d for d in dirnames if not d.startswith((".", "__")) and d not in {"node_modules", "site-packages"}]
            if "GOAL.md" in filenames and "candidate" in dirnames:
                found.append(cls(Path(dirpath)))
                dirnames[:] = []
            elif depth >= max_depth:
                dirnames[:] = []
        return sorted(found, key=lambda c: str(c.root))

    @property
    def exists(self) -> bool:
        return self.goal_path.exists()

    @property
    def name(self) -> str:
        return self.root.name

    @property
    def goal(self) -> GoalConfig:
        if self._goal is None:
            self._goal = load_goal(self.goal_path)
        return self._goal

    @property
    def store(self) -> Store:
        if self._store is None:
            self._store = Store(self.db_path)
        return self._store

    # ---- incumbent ---------------------------------------------------------------------
    def load_incumbent(self) -> Incumbent:
        return Incumbent.from_dict(read_json(self.incumbent_path, None))

    def save_incumbent(self, incumbent: Incumbent) -> None:
        incumbent.updated_at = now_iso()
        write_json(self.incumbent_path, incumbent.to_dict())
        self.store.set("incumbent", incumbent.to_dict())

    def beam(self, k: int = 3) -> list[dict[str, Any]]:
        """The top-k distinct accepted experiments by the primary metric — a small population of strong
        candidates (KernelAgent's beam), not just the single incumbent. Measured facts; the keep/revert
        lineage still promotes the global best as the incumbent, but the beam lets the search see (and
        explore around) other strong points instead of collapsing to one."""
        keeps = [e for e in self.store.list_experiments()
                 if e.get("status") in ("keep", "baseline") and e.get("commit") and e.get("primary_value") is not None]
        keeps.sort(key=lambda e: e["primary_value"], reverse=not self.goal.minimize)
        seen: set[str] = set()
        out: list[dict[str, Any]] = []
        for e in keeps:
            commit = e["commit"]
            if commit in seen:
                continue
            seen.add(commit)
            out.append({"number": e["number"], "commit": commit, "value": e["primary_value"],
                        "description": (e.get("description") or "")[:80]})
            if len(out) >= k:
                break
        return out

    def streak(self) -> dict[str, Any]:
        """How long the campaign has gone without a measured improvement -- the plateau signal.

        Counts consecutive finished experiments since the last keep/bank (a re-measurement of the
        incumbent is neither). `on_target` is the length of the run of *that same target* at the tail,
        so the agent can tell "this target is exhausted" from "the search as a whole has stalled"."""
        experiments = [e for e in self.store.list_experiments() if e.get("status") not in ("running", "remeasure", None)]
        run: list[dict[str, Any]] = []
        for e in reversed(experiments):
            if e.get("status") in ("keep", "bank", "baseline"):
                break
            run.append(e)
        last_target = run[0].get("target") if run else None
        on_target = 0
        for e in run:
            if last_target and e.get("target") == last_target:
                on_target += 1
            else:
                break
        classes = [e.get("failure_class") for e in run if e.get("failure_class")]
        return {"no_improvement": len(run), "target": last_target, "on_target": on_target,
                "failure_classes": classes[:6], "last_status": experiments[-1].get("status") if experiments else None}

    # ---- control flags -----------------------------------------------------------------
    def flag(self, name: str) -> Path:
        return self.state_dir / name

    def set_flag(self, name: str, content: str = "") -> None:
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.flag(name).write_text(content or now_iso(), encoding="utf-8")

    def clear_flag(self, name: str) -> None:
        try:
            self.flag(name).unlink()
        except FileNotFoundError:
            pass

    def has_flag(self, name: str) -> bool:
        return self.flag(name).exists()

    # ---- protection --------------------------------------------------------------------
    def is_protected(self, path: Path | str) -> bool:
        try:
            rel = Path(path).resolve().relative_to(self.root).as_posix()
        except ValueError:
            return False
        for pattern in self.goal.protected:
            pat = pattern.rstrip("/")
            if rel == pat or fnmatch.fnmatch(rel, pat) or (pat.endswith("/**") and rel.startswith(pat[:-3] + "/")):
                return True
        return False

    # ---- git ---------------------------------------------------------------------------
    def git(self, *args: str, check: bool = False, timeout: float = 120, raw: bool = False) -> str:
        """Run git in the campaign. raw=True keeps stdout byte-exact (diffs must end with a newline to apply)."""
        result = run(["git", *args], cwd=self.root, timeout=timeout)
        if check and not result.ok:
            raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip() or result.stdout.strip()}")
        return result.stdout if raw else result.stdout.strip()

    @staticmethod
    def _patch_text(diff: str) -> str:
        return diff if (not diff.strip() or diff.endswith("\n")) else diff + "\n"

    def git_available(self) -> bool:
        return run(["git", "--version"]).ok

    def branch_name(self) -> str:
        return f"fast-kernel/{self.goal.model}"

    def ensure_git(self) -> None:
        if not (self.root / ".git").exists():
            self.git("init", "-q", "-b", self.branch_name(), check=True)
            self.git("config", "user.email", "fast-kernel@local")
            self.git("config", "user.name", "fast-kernel")
        ignore = self.root / ".gitignore"
        if not ignore.exists() or "managed by fast-kernel" not in ignore.read_text(encoding="utf-8"):
            ignore.write_text(CAMPAIGN_IGNORE, encoding="utf-8")
        if self.git("rev-parse", "--verify", "-q", "HEAD") == "":
            self.git("add", "-A")
            self.git("commit", "-q", "-m", "fast-kernel: campaign scaffold", "--allow-empty", check=True)

    def head(self) -> str:
        return self.git("rev-parse", "--short=10", "HEAD")

    def candidate_diff(self) -> str:
        """Diff of the agent-owned tree against the incumbent (HEAD), including untracked files."""
        self.git("add", "-N", "--", "candidate")
        return self._patch_text(self.git("diff", "--", "candidate", raw=True))

    def candidate_dirty(self) -> bool:
        return bool(self.git("status", "--porcelain", "--", "candidate"))

    def commit_candidate(self, message: str, tag: str | None = None) -> str:
        self.git("add", "-A", "--", "candidate")
        self.git("commit", "-q", "-m", message, "--allow-empty", check=True)
        if tag:
            self.git("tag", "-f", tag)
        return self.head()

    def restore_candidate(self) -> None:
        """Reset the agent-owned tree to the incumbent (rejected experiment)."""
        self.git("reset", "-q", "--", "candidate")
        self.git("checkout", "-q", "--", "candidate")
        self.git("clean", "-fdq", "--", "candidate")

    # ---- experiments -------------------------------------------------------------------
    def experiment_dir(self, number: int, slug: str) -> Path:
        return self.experiments_dir / f"{number:04d}-{slug}"

    def list_experiment_dirs(self) -> list[Path]:
        if not self.experiments_dir.exists():
            return []
        return sorted(p for p in self.experiments_dir.iterdir() if p.is_dir())

    def summary(self) -> dict[str, Any]:
        incumbent = self.load_incumbent()
        experiments = self.store.list_experiments()
        baseline = next((e for e in experiments if e.get("number") == 0), None)
        baseline_value = (baseline or {}).get("primary_value")
        speedup = None
        if baseline_value and incumbent.value:
            speedup = baseline_value / incumbent.value if self.goal.minimize else incumbent.value / baseline_value
        counts: dict[str, int] = {}
        for exp in experiments:
            counts[exp.get("status", "?")] = counts.get(exp.get("status", "?"), 0) + 1
        return {
            "name": self.name, "root": str(self.root), "model": self.goal.model, "objective": self.goal.objective,
            "target_metric": self.goal.target_metric, "direction": self.goal.direction,
            "min_improvement": self.goal.min_improvement, "continuous": self.goal.continuous,
            "experiments": len(experiments), "counts": counts,
            "incumbent": incumbent.to_dict(), "baseline_value": baseline_value, "speedup_vs_baseline": speedup,
            "loop_active": self.has_flag("loop.active"), "paused": self.has_flag("paused"),
            "branch": self.branch_name(), "head": self.head() if (self.root / ".git").exists() else "",
            "updated_at": now_iso(),
        }
