"""Render hotspots.json + PLAN.md for the agent."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ..util import fmt, now_iso, write_json


def write_plan(campaign_root: Path, *, profile: dict[str, Any], targets: list[dict[str, Any]], device: dict[str, Any],
               workload: str, experiment: int | None, spec_notes: str = "", backends: dict[str, Any] | None = None) -> None:
    root = Path(campaign_root)
    payload = {
        "generated_at": now_iso(), "workload": workload, "experiment": experiment,
        "summary": {
            "wall_ms": profile.get("wall_ms"), "gpu_busy_ms": profile.get("gpu_busy_ms"), "gpu_time_ms": profile.get("gpu_time_ms"),
            "gpu_busy_ratio": profile.get("gpu_busy_ratio"), "kernel_count": profile.get("kernel_count"),
            "avg_kernel_us": profile.get("avg_kernel_us"), "launch_bound": profile.get("launch_bound"),
        },
        "device": {k: device.get(k) for k in ("name", "compute_capability", "sm_count", "total_memory_gb", "measured_bandwidth_gbs",
                                             "measured_bf16_tflops", "measured_fp32_tflops", "launch_latency_us")},
        "targets": targets,
        "top_kernels": profile.get("kernels", [])[:25],
        "top_ops": profile.get("ops", [])[:25],
    }
    write_json(root / "hotspots.json", payload)
    (root / "PLAN.md").write_text(render_plan_md(payload, spec_notes, backends or {}), encoding="utf-8")


def render_plan_md(payload: dict[str, Any], spec_notes: str = "", backends: dict[str, Any] | None = None) -> str:
    s = payload["summary"]
    d = payload["device"]
    lines = [
        "# Optimization plan (auto-generated by `fast-kernel profile`)",
        "",
        f"_Generated {payload['generated_at']} for workload `{payload['workload']}`"
        + (f" after experiment #{payload['experiment']}" if payload.get("experiment") is not None else "") + "._",
        "",
        "## Where the time goes",
        "",
        f"- wall time per call: **{fmt(s.get('wall_ms'))} ms**; GPU busy: **{fmt(s.get('gpu_busy_ms'))} ms** "
        f"({fmt((s.get('gpu_busy_ratio') or 0) * 100, 3)}% of wall); summed kernel time: {fmt(s.get('gpu_time_ms'))} ms",
        f"- kernel launches per call: **{s.get('kernel_count')}** (avg {fmt(s.get('avg_kernel_us'), 3)} us each)",
        f"- measured state: **{'LAUNCH/OVERHEAD BOUND -- the GPU is idle most of the wall time' if s.get('launch_bound') else 'GPU-BOUND -- most of the wall time is inside kernels'}**",
        f"- device: {d.get('name')} (sm_{str(d.get('compute_capability', '')).replace('.', '')}, {d.get('sm_count')} SMs, "
        f"{fmt(d.get('total_memory_gb'), 3)} GB), measured {fmt(d.get('measured_bandwidth_gbs'), 4)} GB/s, "
        f"{fmt(d.get('measured_bf16_tflops'), 4)} bf16 TFLOPS, launch latency ~{fmt(d.get('launch_latency_us'), 3)} us",
        "",
        "## Ranked targets (by measured share of GPU time)",
        "",
        "_Measured facts only. Which technique or backend to try is yours to discover from the profile,"
        " the top kernels, KNOWLEDGE.md and the backend skills -- nothing here prescribes a method or"
        " predicts how much it will help._",
        "",
        "| # | target | category | bound | share | GPU us | kernels | inst. | tried/accepted |",
        "|--:|---|---|---|--:|--:|--:|--:|--:|",
    ]
    for t in payload["targets"]:
        lines.append(
            f"| {t['rank']} | `{t['class']}` | {t['category']} | {t['boundness']} | {t['fraction'] * 100:.1f}% | "
            f"{fmt(t['gpu_us'], 5)} | {t['kernel_count']} | {t.get('instance_count', 1)} | "
            f"{t.get('attempts', 0)}/{t.get('accepted', 0)} |")
    lines.append("")
    for t in payload["targets"][:10]:
        lines.append(f"### {t['rank']}. {t['title']}  `{t['id']}`")
        if t.get("hint"):
            lines.append(f"- hint: {t['hint']}")
        if t.get("instances"):
            inst = t["instances"][0]
            shapes = inst.get("shapes") or {}
            lines.append(f"- example instance: `{inst['path']}` {fmt(inst['gpu_us'], 5)} us / {inst['kernel_count']} kernels, "
                         f"avg kernel {inst.get('avg_kernel_us')} us; shapes: inputs={shapes.get('inputs')} output={shapes.get('output')} "
                         f"params={shapes.get('params')} attrs={shapes.get('attrs')}")
        if t.get("flops"):
            lines.append(f"- est. {t['flops'] / 1e9:.3f} GFLOP, {t['bytes'] / 1e6:.2f} MB per call")
        if t.get("attempts"):
            lines.append(f"- experiments on this target so far: {t.get('attempts', 0)} tried, {t.get('accepted', 0)} accepted "
                         f"(see KNOWLEDGE.md for what was learned)")
        lines.append("")
    if payload.get("top_kernels"):
        lines.append("## Top kernels")
        lines.append("")
        lines.append("| kernel | count | GPU us | category |")
        lines.append("|---|--:|--:|---|")
        for k in payload["top_kernels"][:15]:
            lines.append(f"| `{k['name'][:70]}` | {k['count']} | {fmt(k['gpu_us'], 5)} | {k['category']} |")
        lines.append("")
    if backends:
        lines.append("## Backends on this machine (evidence, not limits)")
        lines.append("")
        for name, info in backends.items():
            state = "ready" if info.get("compiled") else ("importable" if info.get("available") else "missing")
            extra = f" -- {info.get('error')}" if info.get("error") else ""
            lines.append(f"- **{name}**: {state} (v{info.get('version') or '?'}){extra}")
        lines.append("")
    if spec_notes:
        lines.append("## Model notes")
        lines.append("")
        lines.append(spec_notes.strip())
        lines.append("")
    return "\n".join(lines)
